FROM centos:6

RUN yum install -y epel-release && \
        yum groupinstall -y "Development Tools" && \
        yum install -y wget make git gzip rpm-build yum-utils nc rpmdevtools && \
        yum install -y https://download.postgresql.org/pub/repos/yum/11/redhat/rhel-6-x86_64/pgdg-centos11-11-2.noarch.rpm && \
        yum install -y postgresql11-server postgresql11-contrib && \
        yum clean all

RUN wget https://storage.googleapis.com/golang/go1.9.4.linux-amd64.tar.gz -O /tmp/go.tar.gz && \
        tar xvf /tmp/go.tar.gz -C /usr/local && \
        ln -s /usr/local/go/bin/* /usr/bin/ && \
        GOPATH=/tmp/glua go get --tags 'sqlite' github.com/vadv/gopher-lua-libs/cmd/glua-libs && \
        install /tmp/glua/bin/glua-libs /usr/local/bin && \
        rm -rf /tmp/glua && rm -rf /usr/local/go

RUN mkdir /pg && chown postgres -R /pg

COPY ./schema /schema

USER postgres
RUN /usr/pgsql-11/bin/initdb -D /pg/manager && \
    sed -i 's|#port = 5432|port=5432|g' /pg/manager/postgresql.conf && \
    sed -i "s|#listen_addresses = 'localhost'|listen_addresses='*'|g" /pg/manager/postgresql.conf && \
    /usr/pgsql-11/bin/pg_ctl start -D /pg/manager -w && \
    psql -Atc "create database manager" && \
    psql -1 -d manager -f /schema/manager/schema.sql && \
    psql -1 -d manager -f /schema/manager/functions.sql && \
    psql -Atc "create user agent password 'agent_password'" && \
    psql -d manager -Atc "grant usage on schema agent to agent" && \
    psql -d manager -Atc "grant execute on all functions in schema agent to agent" && \
    psql -Atc "create user manager password 'manager_password'" && \
    psql -d manager -Atc "grant usage on schema manager to manager" && \
    psql -d manager -Atc "grant execute on all functions in schema manager to manager" && \
    psql -d manager -Atc "grant SELECT ON ALL tables in schema manager to manager" && \
    psql -d manager -Atc "alter default privileges in schema manager grant select ON tables TO manager" && \
    psql -d manager -Atc "\
        insert into manager.host(name, agent_token, agent_connection, additional_agent_connections) \
            values ('localhost', 'Xi7ooChu', 'host=/tmp port=5433 user=mon_agent password=mon_agent_password dbname=target_1', \
            '{\" host=/tmp port=5433 user=mon_agent password=mon_agent_password dbname=target_2 \"}'::text[]) " &&\

    /usr/pgsql-11/bin/initdb -D /pg/target && \
    sed -i 's|#port = 5432|port=5433|g' /pg/target/postgresql.conf && \
    sed -i "s|#listen_addresses = 'localhost'|listen_addresses='*'|g" /pg/target/postgresql.conf && \
    /usr/pgsql-11/bin/pg_ctl start -D /pg/target -w && \
    psql -Atc "create database target_1" -p 5433 && \
    psql -Atc "create database target_2" -p 5433 && \
    AGENT_PRIV="host=/tmp dbname=target_1 user=postgres port=5433" /usr/local/bin/glua-libs /schema/agent/deploy.lua && \
    AGENT_PRIV="host=/tmp dbname=target_2 user=postgres port=5433" /usr/local/bin/glua-libs /schema/agent/deploy.lua && \
    psql -p 5433 -Atc "create user mon_agent password 'mon_agent_password'" && \
    psql -p 5433 -d target_1 -Atc "grant usage on schema gatherer to mon_agent" && \
    psql -p 5433 -d target_1 -Atc "grant execute on all functions in schema gatherer to mon_agent" && \
    psql -p 5433 -d target_2 -Atc "grant usage on schema gatherer to mon_agent" && \
    psql -p 5433 -d target_2 -Atc "grant execute on all functions in schema gatherer to mon_agent" && \
    psql -p 5433 -Atc "alter system set shared_preload_libraries to pg_stat_statements" && \

    /usr/pgsql-11/bin/pg_ctl stop -D /pg/manager -w && \
    /usr/pgsql-11/bin/pg_ctl stop -D /pg/target -w

RUN echo "#!/bin/sh -ex" > /pg/start.sh
RUN echo "/usr/pgsql-11/bin/pg_ctl start -D /pg/manager -w" >> /pg/start.sh
RUN echo "/usr/pgsql-11/bin/pg_ctl start -D /pg/target -w" >> /pg/start.sh
RUN chmod +x /pg/*.sh

ENV TOKEN="Xi7ooChu"
ENV MANAGER="host=/tmp user=agent password=agent_password dbname=manager"
ENV CACHE_PATH="/tmp"
