{
 "title": "PostgreSQL (pg_gatherer)",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "select name from manager.host order by name;"
   }
  ]
 },
 "panels": [
  { "title": "Stat", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "max",
   "targets": [
    {
     "rawSql": "SELECT\n  ts as \"time\",\n  value_bigint\nfrom manager.metric where\n  $__unixEpochFilter(ts) AND\n  host = md5('$host')::uuid AND\n  plugin = md5('pg.uptime')::uuid\norder by ts;\n"
    }
   ]
  },
  {
   "title": "Size",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 4, "y": 1 },
   "format": "decbytes",
   "valueName": "max",
   "targets": [
    {
     "rawSql": "SELECT\n  ts as \"time\",\n  sum( coalesce((value_jsonb->>'size')::float8, 0) )\nfrom manager.metric where\n  $__unixEpochFilter(ts) AND\n  host = md5('$host')::uuid AND\n  plugin = md5('pg.databases')::uuid\ngroup by ts\norder by ts;\n"
    }
   ]
  },
  {
   "title": "Wal generation",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 7, "y": 1 },
   "format": "Bps",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  ts as \"time\",\n  value_double as \"value\"\nfrom manager.metric where\n  $__unixEpochFilter(ts) AND\n  host = md5('$host')::uuid AND\n  plugin = md5('pg.wal.speed')::uuid\n\n"
    }
   ]
  },
  {
   "title": "Replication lag",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 11, "y": 1 },
   "format": "Bps",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  ts as \"time\",\n  value_double as \"value\"\nfrom manager.metric where\n  $__unixEpochFilter(ts) AND\n  host = md5('$host')::uuid AND\n  plugin = md5('pg.wal.replication_time_lag')::uuid\n\n"
    }
   ]
  },
  {
   "title": "Slots",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 15, "y": 1 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "with slots as (\n select\n  distinct(jsonb_object_keys(value_jsonb)) as name\n from manager.metric where\n  $__unixEpochFilter(ts) AND\n  host = md5('$host')::uuid AND\n  plugin = md5('pg.replication_slots')::uuid\n)\nSELECT\n  ts as \"time\",\n  max( coalesce((m.value_jsonb->>(s.name))::bigint, 0) ) as \"value\"\nfrom manager.metric m, slots s\nwhere\n  $__unixEpochFilter(ts) AND\n  host = md5('$host')::uuid AND\n  plugin = md5('pg.replication_slots')::uuid\ngroup by ts\norder by ts\n\n"
    }
   ]
  },
  {
   "title": "Buffer Pool hit ratio",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 19, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  ts as \"time\",\n  sum( coalesce((value_jsonb->>'blks_hit')::float8, 0) ) / (1 + sum( coalesce((value_jsonb->>'blks_read')::float8, 0) ) + sum( coalesce((value_jsonb->>'blks_hit')::float8, 0) ) )\nfrom manager.metric where\n  $__unixEpochFilter(ts) AND\n  host = md5('$host')::uuid AND\n  plugin = md5('pg.databases')::uuid\ngroup by ts\norder by ts;\n"
    }
   ]
  },
  {
   "title": "TPS",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 3 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  ts as \"time\",\n  sum( coalesce((value_jsonb->>'xact_commit')::float8, 0) + coalesce((value_jsonb->>'xact_rollback')::float8, 0) )\nfrom manager.metric where\n  $__unixEpochFilter(ts) AND\n  host = md5('$host')::uuid AND\n  plugin = md5('pg.databases')::uuid\ngroup by metric.ts\norder by ts;\n"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 3 },
   "format": "ops",
   "valueName": "max",
   "targets": [
    {
     "rawSql": "SELECT\n  snapshot as \"time\",\n  sum((value_jsonb->>'xact_rollback')::float8)\nfrom manager.metric where\n  $__unixEpochFilter(ts) AND\n  host = md5('$host')::uuid AND\n  plugin = md5('pg.databases')::uuid\ngroup by snapshot\norder by snapshot;\n"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 6, "y": 3 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  snapshot as \"time\",\n  sum((value_jsonb->>'calls')::float8) / 60\nfrom manager.metric where\n  $__unixEpochFilter(ts) AND\n  host = md5('$host')::uuid AND\n  plugin = md5('pg.statements')::uuid\ngroup by snapshot\norder by snapshot;\n"
    }
   ]
  },
  {
   "title": "Query Time (Avg)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 3 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  snapshot as \"time\",\n  sum(coalesce((value_jsonb->>'total_time')::float8,0)) / ( sum(coalesce((value_jsonb->>'calls')::float8, 0)) + 1)\nfrom manager.metric where\n  $__unixEpochFilter(ts) AND\n  host = md5('$host')::uuid AND\n  plugin = md5('pg.statements')::uuid\ngroup by snapshot\norder by snapshot;\n"
    }
   ]
  },
  {
   "title": "Longest query",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 13, "y": 3 },
   "format": "s",
   "valueName": "max",
   "targets": [
    {
     "rawSql": "SELECT\n  snapshot as \"time\",\n  max( coalesce((value_jsonb->>'query_start_duration')::bigint, 0) )\nfrom manager.metric where\n  $__unixEpochFilter(ts) AND\n  host = md5('$host')::uuid AND\n  plugin = md5('pg.activity')::uuid AND\n  NOT value_jsonb->>'query' ~ '^autovacuum: '\ngroup by snapshot\norder by snapshot;\n"
    }
   ]
  },
  {
   "title": "idle in tx",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  snapshot as \"time\",\n  sum(coalesce((value_jsonb->>'count')::float8,0))\nfrom manager.metric where\n  $__unixEpochFilter(ts) AND\n  host = md5('$host')::uuid AND\n  plugin = md5('pg.activity.waits')::uuid AND\n  value_jsonb->>'state' = 'idle in transaction'\ngroup by snapshot\norder by snapshot;\n"
    }
   ]
  },
  {
   "title": "Waiting queries",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  snapshot as \"time\",\n  sum((value_jsonb->>'count')::float8)\nfrom manager.metric where\n  $__unixEpochFilter(ts) AND\n  host = md5('$host')::uuid AND\n  plugin = md5('pg.activity.waits')::uuid AND\n  value_jsonb->>'state' <> 'idle in transaction'\ngroup by snapshot\norder by snapshot;\n"
    }
   ]
  },
  {
   "title": "Seq Scan (> 256MB)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 6, "y": 5 },
   "format": "short",
   "valueName": "max",
   "targets": [
    {
     "rawSql": "SELECT\n  snapshot as \"time\",\n  sum( coalesce((value_jsonb->>'seq_scan')::float8, 0) )\nfrom manager.metric where\n  $__unixEpochFilter(ts) AND\n  host = md5('$host')::uuid AND\n  plugin = md5('pg.user_tables')::uuid AND\n  coalesce((value_jsonb->>'relpages')::bigint, 0)> (256*1024*1024) / (8*1024)\ngroup by snapshot\norder by snapshot;\n"
    }
   ]
  },
  {
   "title": "Bloat (tuples)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 5 },
   "format": "percentunit",
   "valueName": "max",
   "targets": [
    {
     "rawSql": "SELECT\n  snapshot as \"time\",\n  sum(coalesce((value_jsonb->>'n_dead_tup')::bigint, 0)) / sum(coalesce((value_jsonb->>'n_live_tup')::bigint, 0))\nfrom manager.metric where\n  $__unixEpochFilter(ts) AND\n  host = md5('$host')::uuid AND\n  plugin = md5('pg.user_tables')::uuid\n--  AND coalesce((value_jsonb->>'relpages')::bigint, 0)> (256*1024*1024) / (8*1024)\ngroup by snapshot\norder by snapshot;\n"
    }
   ]
  },
  {
   "title": "Dirty buffers",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 13, "y": 5 },
   "format": "percentunit",
   "valueName": "max",
   "targets": [
    {
     "rawSql": "WITH dirty as (\r\n    SELECT\r\n      m.snapshot AS \"time\",\r\n      sum( (m.value_jsonb->>'buffers')::bigint )*8*1024 as \"size\"\r\n    FROM manager.metric m\r\n    WHERE\r\n      $__unixEpochFilter(m.ts) AND\r\n      m.host = md5('$host')::uuid AND\r\n      m.plugin = md5('pg.buffercache')::uuid AND\r\n      (m.value_jsonb->>'dirty')::bool = true\r\n    GROUP BY 1\r\n    ORDER BY 1\r\n),\r\nclean as (\r\n    SELECT\r\n      m.snapshot AS \"time\",\r\n      sum( (m.value_jsonb->>'buffers')::bigint )*8*1024 as \"size\"\r\n    FROM manager.metric m\r\n    WHERE\r\n      $__unixEpochFilter(m.ts) AND\r\n      m.host = md5('$host')::uuid AND\r\n      m.plugin = md5('pg.buffercache')::uuid AND\r\n      (m.value_jsonb->>'dirty')::bool = false\r\n    GROUP BY 1\r\n    ORDER BY 1\r\n)\r\n\r\nSELECT\r\n    clean.time,\r\n    (dirty.size / (clean.size + dirty.size + 1)) as \"value\"\r\nFROM clean\r\nINNER JOIN dirty on dirty.time = clean.time "
    }
   ]
  },
  {
   "title": "Buffer pool reuse",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 16, "y": 5 },
   "format": "percentunit",
   "valueName": "max",
   "targets": [
    {
     "rawSql": "WITH once as (\r\n    SELECT\r\n      m.snapshot AS \"time\",\r\n      sum( (m.value_jsonb->>'buffers')::bigint )*8*1024 as \"size\"\r\n    FROM manager.metric m\r\n    WHERE\r\n      $__unixEpochFilter(m.ts) AND\r\n      m.host = md5('$host')::uuid AND\r\n      m.plugin = md5('pg.buffercache')::uuid AND\r\n      (m.value_jsonb->>'usagecount')::bigint = 0\r\n    GROUP BY 1\r\n    ORDER BY 1\r\n),\r\ntotal as (\r\n    SELECT\r\n      m.snapshot AS \"time\",\r\n      sum( (m.value_jsonb->>'buffers')::bigint )*8*1024 as \"size\"\r\n    FROM manager.metric m\r\n    WHERE\r\n      $__unixEpochFilter(m.ts) AND\r\n      m.host = md5('$host')::uuid AND\r\n      m.plugin = md5('pg.buffercache')::uuid\r\n    GROUP BY 1\r\n    ORDER BY 1\r\n)\r\n\r\nSELECT\r\n    total.time,\r\n    (1-(once.size / (total.size + once.size + 1))) as \"value\"\r\nFROM total\r\nINNER JOIN once on once.time = total.time "
    }
   ]
  },
  {
   "title": "Databases",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "databases",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
     "targets": [
      {
       "application": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "rawSql": "select\r\n    value_jsonb->>'datname' as \"name\",\r\n    pg_catalog.pg_size_pretty((max(value_jsonb->>'size')::bigint)) as \"size\",\r\n    max( (value_jsonb->>'age')::bigint ) as \"age\",\r\n    sum( (value_jsonb->>'conflicts')::float8 ) as \"conflicts\",\r\n    sum( (value_jsonb->>'temp_files')::float8 ) as \"temp files\",\r\n    TO_CHAR(( sum( (value_jsonb->>'blk_read_time')::float8  )  * interval '1 millisecond' ) , 'HH24:MI:SS') as \"read time\",\r\n    TO_CHAR(( sum( (value_jsonb->>'blk_write_time')::float8  )  * interval '1 millisecond' ) , 'HH24:MI:SS') as \"write time\",\r\n    avg( (value_jsonb->>'xact_commit')::float8 ) as \"commits\",\r\n    avg( (value_jsonb->>'xact_rollback')::float8 ) as \"rollback\"\r\n    from manager.metric where\r\n        $__unixEpochFilter(ts) AND\r\n        host = md5('$host')::uuid AND\r\n        plugin = md5('pg.databases')::uuid\r\n    group by 1\r\n    order by 1",
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    }
   ]
  },
  {
   "title": "Backend states",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Backend states",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "rawSql": "SELECT\r\n  ts AS \"time\",\r\n--  (value_jsonb->>'idle')::int as \"idle\",\r\n  (value_jsonb->>'active')::int as \"active\",\r\n  (value_jsonb->>'idle in transaction')::int as \"idle in transaction\",\r\n  (value_jsonb->>'idle in transaction (aborted)')::int as \"idle in transaction (aborted)\",\r\n  (value_jsonb->>'fastpath function call')::int as \"fastpath function call\"\r\nFROM manager.metric\r\nWHERE\r\n  $__unixEpochFilter(ts) AND\r\n  host = md5('$host')::uuid AND\r\n  plugin = md5('pg.activity.states')::uuid\r\nORDER BY 1",
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    }
   ]
  },
  {
   "title": "Statements",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "statements (most disk)",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
     "targets": [
      {
       "application": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "rawSql": "select\r\n    value_jsonb->>'dbname' as \"database\",\r\n    value_jsonb->>'query' as \"query\",\r\n    sum( coalesce( (value_jsonb->>'calls')::bigint, 0 ) ) as \"calls\",\r\n    pg_size_pretty(\r\n      (sum(\r\n        coalesce((value_jsonb->>'shared_blks_read')::float8, 0)\r\n        + coalesce((value_jsonb->>'local_blks_read')::float8, 0)\r\n        + coalesce((value_jsonb->>'temp_blks_read')::float8, 0)\r\n      )*8*1024)::bigint\r\n    ) as \"r (b)\",\r\n    pg_size_pretty(\r\n      (sum(\r\n        coalesce((value_jsonb->>'shared_blks_written')::float8, 0)\r\n        + coalesce((value_jsonb->>'local_blks_written')::float8, 0)\r\n        + coalesce((value_jsonb->>'local_blks_dirtied')::float8, 0)\r\n        + coalesce((value_jsonb->>'temp_blks_written')::float8, 0)\r\n      )*8/1024)::bigint\r\n    ) as \"w (b)\",\r\n    TO_CHAR( sum(coalesce((value_jsonb->>'blk_read_time')::float8, 0)) * interval '1 second' , 'HH24:MI:SS') as  \"r(s)\",\r\n    TO_CHAR( sum(coalesce((value_jsonb->>'blk_write_time')::float8, 0)) * interval '1 second' , 'HH24:MI:SS') as  \"w(s)\"\r\n    from manager.metric where\r\n        $__unixEpochFilter(ts) AND\r\n        host = md5('$host')::uuid AND\r\n        plugin = md5('pg.statements')::uuid\r\n    group by 1,2\r\n    having\r\n    sum(\r\n        coalesce((value_jsonb->>'shared_blks_read')::float8, 0)\r\n        + coalesce((value_jsonb->>'local_blks_read')::float8, 0)\r\n        + coalesce((value_jsonb->>'temp_blks_read')::float8, 0)\r\n        + coalesce((value_jsonb->>'shared_blks_written')::float8, 0)\r\n        + coalesce((value_jsonb->>'local_blks_written')::float8, 0)\r\n        + coalesce((value_jsonb->>'local_blks_dirtied')::float8, 0)\r\n        + coalesce((value_jsonb->>'temp_blks_written')::float8, 0)\r\n    ) > 0\r\n    order by sum(\r\n        coalesce((value_jsonb->>'shared_blks_read')::float8, 0)\r\n        + coalesce((value_jsonb->>'local_blks_read')::float8, 0)\r\n        + coalesce((value_jsonb->>'temp_blks_read')::float8, 0)\r\n        + coalesce((value_jsonb->>'shared_blks_written')::float8, 0)\r\n        + coalesce((value_jsonb->>'local_blks_written')::float8, 0)\r\n        + coalesce((value_jsonb->>'local_blks_dirtied')::float8, 0)\r\n        + coalesce((value_jsonb->>'temp_blks_written')::float8, 0)\r\n    ) desc",
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "statements (most temp files)",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
     "targets": [
      {
       "application": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "rawSql": "select\r\n    value_jsonb->>'dbname' as \"database\",\r\n    value_jsonb->>'query' as \"query\",\r\n    pg_size_pretty(\r\n      (sum( \r\n        coalesce((value_jsonb->>'temp_blks_written')::float8, 0)\r\n        + coalesce((value_jsonb->>'temp_blks_read')::float8, 0)\r\n       ))::bigint*8*1024\r\n    ) as \"size\"\r\n    from manager.metric where\r\n        $__unixEpochFilter(ts) AND\r\n        host = md5('$host')::uuid AND\r\n        plugin = md5('pg.statements')::uuid\r\n    group by 1,2\r\n    having sum( \r\n        coalesce((value_jsonb->>'temp_blks_written')::float8, 0)\r\n        + coalesce((value_jsonb->>'temp_blks_read')::float8, 0)\r\n      ) > 0\r\n    order by \r\n      sum( \r\n        coalesce((value_jsonb->>'temp_blks_written')::float8, 0)\r\n        + coalesce((value_jsonb->>'temp_blks_read')::float8, 0)\r\n      ) desc\r\n    limit 20",
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "statements (most time)",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
     "targets": [
      {
       "application": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "rawSql": "select\r\n    value_jsonb->>'dbname' as \"database\",\r\n    value_jsonb->>'query' as \"query\",\r\n    sum( coalesce( (value_jsonb->>'calls')::bigint, 0 ) ) as \"calls\",\r\n    TO_CHAR( sum(coalesce((value_jsonb->>'total_time')::float8, 0)) * interval '1 second' , 'HH24:MI:SS') as \"total_time\"\r\n    from manager.metric where\r\n        $__unixEpochFilter(ts) AND\r\n        host = md5('$host')::uuid AND\r\n        plugin = md5('pg.statements')::uuid AND\r\n        value_jsonb->>'query' <> 'BEGIN' AND\r\n        value_jsonb->>'query' <> 'BEGIN READ WRITE' AND\r\n        value_jsonb->>'query' <> 'COMMIT' AND\r\n        value_jsonb->>'query' <> 'ROLLBACK'\r\n    group by 1,2\r\n    order by sum(coalesce((value_jsonb->>'total_time')::float8, 0)) desc\r\n    limit 20",
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    }
   ]
  },
  {
   "title": "Locks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "block queries",
     "type": "table",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 11 },
     "targets": [
      {
       "application": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "rawSql": "select\r\n    value_jsonb->>'current_database' as \"dbname\",\r\n    value_jsonb->>'blocked_statement' as \"blocked_statement\",\r\n    value_jsonb->>'current_statement_in_blocking_process' as \"current_statement_in_blocking_process\",\r\n    min(to_timestamp(ts) AT TIME ZONE 'UTC') as \"first seen\",\r\n    max(to_timestamp(ts) AT TIME ZONE 'UTC') as \"last seen\",\r\n    TO_CHAR( (max(ts) - min(ts)) * interval '1 second' , 'HH24:MI:SS') as \"duration\"\r\n    from manager.metric where\r\n        $__unixEpochFilter(ts) AND\r\n        host = md5('$host')::uuid AND\r\n        plugin = md5('pg.block')::uuid\r\n    group by 1,2,3, value_jsonb->>'blocked_query_id', value_jsonb->>'blocking_query_id'\r\n    having\r\n      (max(ts) - min(ts)) > 1\r\n    order by (max(ts) - min(ts)) desc\r\n",
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    }
   ]
  },
  {
   "title": "Long queries (activity)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "activity",
     "type": "table",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 12 },
     "targets": [
      {
       "application": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "rawSql": "select\r\n    value_jsonb->>'datname' as \"datname\",\r\n    value_jsonb->>'query_id' as \"query_id\",\r\n    min(to_timestamp(ts) AT TIME ZONE 'UTC') as \"first seen\",\r\n    max(to_timestamp(ts) AT TIME ZONE 'UTC') as \"last seen\",\r\n    TO_CHAR( (max(ts) - min(ts))::bigint * interval '1 second' , 'HH24:MI:SS') as \"duration\",\r\n    max(value_jsonb->>'query') as \"query\",\r\n    pg_size_pretty((max(value_jsonb->>'rchar')::float8)::bigint) as \"read\",\r\n    pg_size_pretty((max(value_jsonb->>'wchar')::float8)::bigint) as \"write\",\r\n    (max(value_jsonb->>'utime')::float8)/100 as \"cpu_user\",\r\n    (max(value_jsonb->>'stime')::float8)/100 as \"cpu_system\"\r\n    from manager.metric where\r\n        $__unixEpochFilter(ts) AND\r\n        host = md5('$host')::uuid AND\r\n        plugin = md5('pg.activity')::uuid\r\n    group by 1,2\r\n    having  max(ts) - min(ts) > 0\r\n    order by max(value_jsonb->>'rchar')::float8 desc nulls last",
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    }
   ]
  },
  { "title": "Buffer pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Buffer pool per relation",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "rawSql": "WITH tables AS(\r\n    SELECT\r\n        m.value_jsonb->>'full_relation_name' as \"relation\",\r\n        sum( coalesce((m.value_jsonb->>'buffers')::float8, 0) )  as \"rows\"\r\n    FROM manager.metric m\r\n    WHERE\r\n        $__unixEpochFilter(ts) AND\r\n        host = md5('$host')::uuid AND\r\n        plugin = md5('pg.buffercache')::uuid\r\n    GROUP BY 1\r\n    ORDER BY 2 DESC\r\n    LIMIT 20\r\n)\r\nSELECT\r\n  m.snapshot AS \"time\",\r\n  m.value_jsonb->>'full_relation_name' as \"relation\",\r\n  sum( (m.value_jsonb->>'buffers')::bigint )*8*1024 as \"value\"\r\nFROM manager.metric m\r\nINNER JOIN tables t ON t.relation = m.value_jsonb->>'full_relation_name'\r\nWHERE\r\n  $__unixEpochFilter(m.ts) AND\r\n  m.host = md5('$host')::uuid AND\r\n  m.plugin = md5('pg.buffercache')::uuid\r\nGROUP BY 1,2\r\nORDER BY 1,2",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Buffer pool (dirty)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "rawSql": "SELECT\r\n  m.snapshot AS \"time\",\r\n  sum( (m.value_jsonb->>'buffers')::bigint )*8*1024 as \"dirty\"\r\nFROM manager.metric m\r\nWHERE\r\n  $__unixEpochFilter(m.ts) AND\r\n  m.host = md5('$host')::uuid AND\r\n  m.plugin = md5('pg.buffercache')::uuid AND\r\n  (m.value_jsonb->>'dirty')::bool = true\r\nGROUP BY 1\r\nORDER BY 1",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Buffer pool (usagecount = 0)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 26 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "rawSql": "SELECT\r\n  m.snapshot AS \"time\",\r\n  sum( (m.value_jsonb->>'buffers')::bigint )*8*1024 as \"used one time\"\r\nFROM manager.metric m\r\nWHERE\r\n  $__unixEpochFilter(m.ts) AND\r\n  m.host = md5('$host')::uuid AND\r\n  m.plugin = md5('pg.buffercache')::uuid AND\r\n  (m.value_jsonb->>'usagecount')::bigint = 0\r\nGROUP BY 1\r\nORDER BY 1",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Buffer pool (usagecount >= 3)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 26 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "rawSql": "SELECT\r\n  m.snapshot AS \"time\",\r\n  sum( (m.value_jsonb->>'buffers')::bigint )*8*1024 as \"reused\"\r\nFROM manager.metric m\r\nWHERE\r\n  $__unixEpochFilter(m.ts) AND\r\n  m.host = md5('$host')::uuid AND\r\n  m.plugin = md5('pg.buffercache')::uuid AND\r\n  (m.value_jsonb->>'usagecount')::bigint >= 3\r\nGROUP BY 1\r\nORDER BY 1",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Tuples (rows) per table",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Seq scan tuples",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "rawSql": "WITH tables AS(\r\n    SELECT\r\n        m.value_jsonb->>'full_table_name' as \"table\",\r\n        sum( coalesce((m.value_jsonb->>'seq_tup_read')::float8, 0) )  as \"rows\"\r\n    FROM manager.metric m\r\n    WHERE\r\n        $__unixEpochFilter(ts) AND\r\n        host = md5('$host')::uuid AND\r\n        plugin = md5('pg.user_tables')::uuid\r\n    GROUP BY 1\r\n    ORDER BY 2 DESC\r\n    LIMIT 20\r\n)\r\n\r\nSELECT\r\n  m.ts AS \"time\",\r\n  m.value_jsonb->>'full_table_name' as \"table\",\r\n  sum( coalesce((m.value_jsonb->>'seq_tup_read')::float8, 0) ) as \"rows\"\r\nFROM tables t \r\nINNER JOIN manager.metric m ON t.table = m.value_jsonb->>'full_table_name'\r\nWHERE\r\n  $__unixEpochFilter(m.ts) AND\r\n  m.host = md5('$host')::uuid AND\r\n  m.plugin = md5('pg.user_tables')::uuid\r\nGROUP BY 1,2\r\nORDER BY 1,2",
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Index tuples",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "rawSql": "WITH tables AS(\r\n    SELECT\r\n        m.value_jsonb->>'full_table_name' as \"table\",\r\n        sum( coalesce((m.value_jsonb->>'idx_tup_fetch')::float8, 0) )  as \"rows\"\r\n    FROM manager.metric m\r\n    WHERE\r\n        $__unixEpochFilter(ts) AND\r\n        host = md5('$host')::uuid AND\r\n        plugin = md5('pg.user_tables')::uuid\r\n    GROUP BY 1\r\n    ORDER BY 2 DESC\r\n    LIMIT 20\r\n)\r\n\r\nSELECT\r\n  m.ts AS \"time\",\r\n  m.value_jsonb->>'full_table_name' as \"table\",\r\n  sum( coalesce((m.value_jsonb->>'idx_tup_fetch')::float8, 0) ) as \"rows\"\r\nFROM manager.metric m\r\nINNER JOIN tables t ON t.table = m.value_jsonb->>'full_table_name'\r\nWHERE\r\n  $__unixEpochFilter(ts) AND\r\n  host = md5('$host')::uuid AND\r\n  plugin = md5('pg.user_tables')::uuid\r\nGROUP BY 1,2\r\nORDER BY 1,2",
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Changed tuples",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "rawSql": "WITH tables AS(\r\n    SELECT\r\n        m.value_jsonb->>'full_table_name' as \"table\",\r\n        sum( coalesce((m.value_jsonb->>'n_tup_ins')::float8, 0) + coalesce((value_jsonb->>'n_tup_upd')::float8, 0) + coalesce((value_jsonb->>'n_tup_del')::float8, 0) + coalesce((value_jsonb->>'n_tup_hot_upd')::float8, 0) )\r\n    FROM manager.metric m\r\n    WHERE\r\n        $__unixEpochFilter(ts) AND\r\n        host = md5('$host')::uuid AND\r\n        plugin = md5('pg.user_tables')::uuid\r\n    GROUP BY 1\r\n    ORDER BY 2 DESC\r\n    LIMIT 20\r\n)\r\n\r\nSELECT\r\n  m.ts AS \"time\",\r\n  m.value_jsonb->>'full_table_name' as \"table\",\r\n  sum( coalesce((m.value_jsonb->>'n_tup_ins')::float8, 0) + coalesce((value_jsonb->>'n_tup_upd')::float8, 0) + coalesce((value_jsonb->>'n_tup_del')::float8, 0) + coalesce((value_jsonb->>'n_tup_hot_upd')::float8, 0) ) as \"rows\"\r\nFROM manager.metric m\r\nINNER JOIN tables t ON t.table = m.value_jsonb->>'full_table_name'\r\nWHERE\r\n  $__unixEpochFilter(ts) AND\r\n  host = md5('$host')::uuid AND\r\n  plugin = md5('pg.user_tables')::uuid\r\nGROUP BY 1,2\r\nORDER BY 1,2\r\n",
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    }
   ]
  },
  {
   "title": "Read per table",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Heap read (from disk)",
     "type": "graph",
     "gridPos": { "h": 10, "w": 11, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "rawSql": "WITH tables AS(\r\n    SELECT\r\n        m.value_jsonb->>'full_table_name' as \"table\",\r\n        sum( coalesce((m.value_jsonb->>'heap_blks_read')::float8, 0) )  as \"rows\"\r\n    FROM manager.metric m\r\n    WHERE\r\n        $__unixEpochFilter(ts) AND\r\n        host = md5('$host')::uuid AND\r\n        plugin = md5('pg.user_tables.io')::uuid\r\n    GROUP BY 1\r\n    ORDER BY 2 DESC\r\n    LIMIT 20\r\n)\r\n\r\nSELECT\r\n  m.ts AS \"time\",\r\n  m.value_jsonb->>'full_table_name' as \"table\",\r\n  sum( coalesce((m.value_jsonb->>'heap_blks_read')::float8, 0) )  * 8 * 1024 as \"heap\"\r\nFROM manager.metric m\r\nINNER JOIN tables t ON t.table = m.value_jsonb->>'full_table_name'\r\nWHERE\r\n  $__unixEpochFilter(ts) AND\r\n  host = md5('$host')::uuid AND\r\n  plugin = md5('pg.user_tables.io')::uuid\r\nGROUP BY 1,2\r\nORDER BY 1\r\n",
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Toast read (from disk)",
     "type": "graph",
     "gridPos": { "h": 10, "w": 13, "x": 11, "y": 14 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "rawSql": "WITH tables AS(\r\n    SELECT\r\n        m.value_jsonb->>'full_table_name' as \"table\",\r\n        sum( coalesce((m.value_jsonb->>'toast_blks_read')::float8, 0) )  as \"rows\"\r\n    FROM manager.metric m\r\n    WHERE\r\n        $__unixEpochFilter(ts) AND\r\n        host = md5('$host')::uuid AND\r\n        plugin = md5('pg.user_tables.io')::uuid\r\n    GROUP BY 1\r\n    ORDER BY 2 DESC\r\n    LIMIT 20\r\n)\r\n\r\nSELECT\r\n  m.ts AS \"time\",\r\n  m.value_jsonb->>'full_table_name' as \"table\",\r\n  sum( coalesce((m.value_jsonb->>'toast_blks_read')::float8, 0) )  * 8 * 1024 as \"heap\"\r\nFROM manager.metric m\r\nINNER JOIN tables t ON t.table = m.value_jsonb->>'full_table_name'\r\nWHERE\r\n  $__unixEpochFilter(ts) AND\r\n  host = md5('$host')::uuid AND\r\n  plugin = md5('pg.user_tables.io')::uuid\r\nGROUP BY 1,2\r\nORDER BY 1\r\n",
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Index read (from disk)",
     "type": "graph",
     "gridPos": { "h": 10, "w": 11, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "rawSql": "WITH tables AS(\r\n    SELECT\r\n        m.value_jsonb->>'full_table_name' as \"table\",\r\n        sum( coalesce((m.value_jsonb->>'tidx_blks_read')::float8, 0) )  as \"rows\"\r\n    FROM manager.metric m\r\n    WHERE\r\n        $__unixEpochFilter(ts) AND\r\n        host = md5('$host')::uuid AND\r\n        plugin = md5('pg.user_tables.io')::uuid\r\n    GROUP BY 1\r\n    ORDER BY 2 DESC\r\n    LIMIT 20\r\n)\r\n\r\nSELECT\r\n  m.ts AS \"time\",\r\n  m.value_jsonb->>'full_table_name' as \"table\",\r\n  sum( coalesce((m.value_jsonb->>'tidx_blks_read')::float8, 0) )  * 8 * 1024 as \"heap\"\r\nFROM manager.metric m\r\nINNER JOIN tables t ON t.table = m.value_jsonb->>'full_table_name'\r\nWHERE\r\n  $__unixEpochFilter(ts) AND\r\n  host = md5('$host')::uuid AND\r\n  plugin = md5('pg.user_tables.io')::uuid\r\nGROUP BY 1,2\r\nORDER BY 1\r\n",
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    }
   ]
  },
  {
   "title": "Seq scans per table",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "seq scans",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 37 },
     "targets": [
      {
       "application": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "rawSql": "SELECT\r\n  to_timestamp(snapshot) as \"timestamp\",\r\n  value_jsonb->>'full_table_name' as table,\r\n  pg_size_pretty(coalesce((value_jsonb->>'relpages')::bigint, 0)*8*1024) as \"table size\",\r\n  sum( coalesce((value_jsonb->>'seq_scan')::float8, 0) ) as \"count\"\r\nfrom manager.metric where\r\n  $__unixEpochFilter(ts) AND\r\n  host = md5('$host')::uuid AND\r\n  plugin = md5('pg.user_tables')::uuid AND\r\n  coalesce((value_jsonb->>'relpages')::bigint, 0)> (256*1024*1024) / (8*1024)\r\ngroup by 1,2,3,snapshot\r\nhaving sum( coalesce((value_jsonb->>'seq_scan')::float8, 0) ) * 60 > 0\r\norder by snapshot;",
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    }
   ]
  },
  { "title": "Checkpoints", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Checkpoints (count)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "rawSql": "SELECT\r\n  ts AS \"time\",\r\n  (value_jsonb->>'checkpoints_timed')::bigint as \"timed\",\r\n  (value_jsonb->>'checkpoints_req')::bigint as \"required\"\r\nFROM manager.metric\r\nWHERE\r\n  $__unixEpochFilter(ts) AND\r\n  host = md5('$host')::uuid AND\r\n  plugin = md5('pg.bgwriter')::uuid\r\nORDER BY 1",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Checkpoints (time)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 38 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "rawSql": "SELECT\r\n  ts AS \"time\",\r\n  (value_jsonb->>'checkpoint_write_time')::float8 as \"write\",\r\n  (value_jsonb->>'checkpoint_sync_time')::float8 as \"sync\"\r\nFROM manager.metric\r\nWHERE\r\n  $__unixEpochFilter(ts) AND\r\n  host = md5('$host')::uuid AND\r\n  plugin = md5('pg.bgwriter')::uuid\r\nORDER BY 1",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Backend waits",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "Backend states (wait events type)",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "rawSql": "with wait_event_type as (\r\n    select\r\n        distinct(m.value_jsonb->>'wait_event_type') as wait_event_type\r\n    from manager.metric m\r\n    where\r\n        $__unixEpochFilter(ts) AND\r\n        host = md5('$host')::uuid AND\r\n        plugin = md5('pg.activity.waits')::uuid\r\n)\r\n\r\nSELECT\r\n   snapshot AS \"time\",\r\n   sum( coalesce((value_jsonb->>'count')::bigint, 0) ) as event,\r\n   t.wait_event_type\r\nFROM wait_event_type t\r\n    LEFT JOIN manager.metric m on t.wait_event_type = m.value_jsonb->>'wait_event_type'\r\nWHERE\r\n  $__unixEpochFilter(m.ts) AND\r\n  host = md5('$host')::uuid AND\r\n  plugin = md5('pg.activity.waits')::uuid\r\nGROUP BY 1,3\r\nORDER BY 1,3",
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Backend states (wait events)",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 39 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "rawSql": "SELECT\r\n  ts AS \"time\",\r\n   sum((value_jsonb->>'count')::bigint) as event,\r\n   coalesce( (value_jsonb->>'wait_event')::text, 'CPU') as \"wait_event\"\r\nFROM manager.metric\r\nWHERE\r\n  $__unixEpochFilter(ts) AND\r\n  host = md5('$host')::uuid AND\r\n  plugin = md5('pg.activity.waits')::uuid\r\nGROUP BY 1,3\r\nORDER BY 1,3",
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "rawSql": "SELECT\r\n  ts AS \"time\",\r\n  (value_jsonb->>'user')::float8 AS \"user\",\r\n  (value_jsonb->>'nice')::float8 AS \"nice\",\r\n  (value_jsonb->>'system')::float8 AS \"system\",\r\n  (value_jsonb->>'idle')::float8 AS \"idle\",\r\n  (value_jsonb->>'iowait')::float8 AS \"iowait\",\r\n  (value_jsonb->>'irq')::float8 AS \"irq\",\r\n  (value_jsonb->>'softirq')::float8 AS \"softirq\",\r\n  (value_jsonb->>'steal')::float8 AS \"steal\",\r\n  (value_jsonb->>'guest')::float8 AS \"guest\",\r\n  (value_jsonb->>'guest_nice')::float8 AS \"guest_nice\"\r\nFROM manager.metric\r\nWHERE\r\n  $__unixEpochFilter(ts) AND\r\n  host = md5('$host')::uuid AND\r\n  plugin = md5('linux.cpu')::uuid\r\nORDER BY 1",
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "CPU: running/blocked && fork-rate",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 59 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "rawSql": "SELECT\n  ts AS \"time\",\n  value_bigint AS \"running process\"\nFROM manager.metric\nWHERE\n  $__unixEpochFilter(ts) AND\n  host = md5('$host')::uuid AND\n  plugin = md5('linux.cpu.running')::uuid\nORDER BY 1",
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "rawSql": "SELECT\n  ts AS \"time\",\n  value_bigint AS \"blocked process\"\nFROM manager.metric\nWHERE\n  $__unixEpochFilter(ts) AND\n  host = md5('$host')::uuid AND\n  plugin = md5('linux.cpu.blocked')::uuid\nORDER BY 1",
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "rawSql": "SELECT\n  ts AS \"time\",\n  value_double AS \"fork-rate\"\nFROM manager.metric\nWHERE\n  $__unixEpochFilter(ts) AND\n  host = md5('$host')::uuid AND\n  plugin = md5('linux.cpu.fork_rate')::uuid\nORDER BY 1",
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "CPU (RDS)",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 69 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "expr": "sum(aws_rds_cpuutilization_average{dbinstance_identifier=\"$host\"})",
       "host": { "filter": "" },
       "item": { "filter": "" },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "rawSql": "SELECT\r\n  ts AS \"time\",\r\n  (value_jsonb->>'user')::float8 AS \"user\",\r\n  (value_jsonb->>'nice')::float8 AS \"nice\",\r\n  (value_jsonb->>'system')::float8 AS \"system\",\r\n  (value_jsonb->>'idle')::float8 AS \"idle\",\r\n  (value_jsonb->>'iowait')::float8 AS \"iowait\",\r\n  (value_jsonb->>'irq')::float8 AS \"irq\",\r\n  (value_jsonb->>'softirq')::float8 AS \"softirq\",\r\n  (value_jsonb->>'steal')::float8 AS \"steal\",\r\n  (value_jsonb->>'guest')::float8 AS \"guest\",\r\n  (value_jsonb->>'guest_nice')::float8 AS \"guest_nice\"\r\nFROM manager.metric\r\nWHERE\r\n  $__unixEpochFilter(ts) AND\r\n  host = md5('$host')::uuid AND\r\n  plugin = md5('linux.cpu')::uuid\r\nORDER BY 1",
       "region": "default",
       "statistics": [ "Average" ],
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "rawSql": "SELECT\r\n  ts AS \"time\",\r\n  (value_jsonb->>'MemFree')::bigint AS \"MemFree\",\r\n  (value_jsonb->>'Buffers')::bigint AS \"Buffers\",\r\n  (value_jsonb->>'Cached')::bigint AS \"Cached\",\r\n  (value_jsonb->>'Dirty')::bigint AS \"Dirty\",\r\n  (value_jsonb->>'Slab')::bigint AS \"Slab\"\r\n\r\nFROM manager.metric\r\nWHERE\r\n  $__unixEpochFilter(ts) AND\r\n  host = md5('$host')::uuid AND\r\n  plugin = md5('linux.memory')::uuid\r\nORDER BY 1",
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "panels": [
    {
     "title": "Utilization",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "rawSql": "SELECT\r\n  ts AS \"time\",\r\n  value_jsonb->>'mountpoint' as \"mountpoint\",\r\n  sum(coalesce((value_jsonb->>'utilization')::float8,0)) as \"utilization\"\r\nFROM manager.metric\r\nWHERE\r\n  $__unixEpochFilter(ts) AND\r\n  host = md5('$host')::uuid AND\r\n  plugin = md5('linux.diskstats')::uuid\r\nGROUP BY 1,2\r\nORDER BY 1",
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Await",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "rawSql": "SELECT\r\n  ts AS \"time\",\r\n  value_jsonb->>'mountpoint' as \"mountpoint\",\r\n  sum((value_jsonb->>'await')::float8) as \"await\"\r\nFROM manager.metric\r\nWHERE\r\n  $__unixEpochFilter(ts) AND\r\n  host = md5('$host')::uuid AND\r\n  plugin = md5('linux.diskstats')::uuid\r\nGROUP BY 1,2\r\nORDER BY 1",
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "IOPS (RDS)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "expr": "sum(aws_rds_read_iops_average{dbinstance_identifier=\"$host\"})",
       "host": { "filter": "" },
       "item": { "filter": "" },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "rawSql": "SELECT\r\n  ts AS \"time\",\r\n  value_jsonb->>'mountpoint' as \"mountpoint\",\r\n  sum(coalesce((value_jsonb->>'utilization')::float8,0)) as \"utilization\"\r\nFROM manager.metric\r\nWHERE\r\n  $__unixEpochFilter(ts) AND\r\n  host = md5('$host')::uuid AND\r\n  plugin = md5('linux.diskstats')::uuid\r\nGROUP BY 1,2\r\nORDER BY 1",
       "region": "default",
       "statistics": [ "Average" ],
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "" },
       "expr": "sum(aws_rds_write_iops_average{dbinstance_identifier=\"$host\"})",
       "host": { "filter": "" },
       "item": { "filter": "" },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "rawSql": "SELECT\r\n  ts AS \"time\",\r\n  value_jsonb->>'mountpoint' as \"mountpoint\",\r\n  sum(coalesce((value_jsonb->>'utilization')::float8,0)) as \"utilization\"\r\nFROM manager.metric\r\nWHERE\r\n  $__unixEpochFilter(ts) AND\r\n  host = md5('$host')::uuid AND\r\n  plugin = md5('linux.diskstats')::uuid\r\nGROUP BY 1,2\r\nORDER BY 1",
       "region": "default",
       "statistics": [ "Average" ],
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    }
   ]
  },
  {
   "title": "Vacuum activity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "panels": [
    {
     "title": "vacuum activity",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 22 },
     "targets": [
      {
       "application": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "rawSql": "select\r\n    value_jsonb->>'full_table_name' as \"table\",\r\n    max( to_timestamp( (value_jsonb->>'last_autovacuum')::bigint ) AT TIME ZONE 'UTC') as \"last_autovacuum\",\r\n    sum( (value_jsonb->>'autovacuum_count')::bigint ) as \"autovacuum count\", \r\n    max( to_timestamp( (value_jsonb->>'last_autoanalyze')::bigint ) AT TIME ZONE 'UTC') as \"last_autoanalyze\",\r\n    sum( (value_jsonb->>'autoanalyze_count')::bigint ) as \"autoanalyze count\"\r\n    from manager.metric where\r\n        $__unixEpochFilter(ts) AND\r\n        host = md5('$host')::uuid AND\r\n        plugin = md5('pg.user_tables')::uuid\r\n    group by 1\r\n    having (sum( (value_jsonb->>'autovacuum_count')::bigint ) > 0) OR (sum( (value_jsonb->>'autoanalyze_count')::bigint ) > 0)\r\n    order by 5 desc",
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    }
   ]
  },
  {
   "title": "Buffers write",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true,
   "panels": [
    {
     "title": "Buffers write",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "rawSql": "SELECT\r\n  snapshot AS \"time\",\r\n  (value_jsonb->>'buffers_checkpoint')::float8 * 8 * 1024 as \"checkpoint\",\r\n  (value_jsonb->>'buffers_clean')::float8 * 8 * 1024 as \"bgwriter\",\r\n  (value_jsonb->>'buffers_backend')::float8 * 8 * 1024 as \"backend\"\r\nFROM manager.metric\r\nWHERE\r\n  $__unixEpochFilter(ts) AND\r\n  host = md5('$host')::uuid AND\r\n  plugin = md5('pg.bgwriter')::uuid\r\nORDER BY 1",
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    }
   ]
  }
 ]
}