name: latest
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'

jobs:

  test:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Build and push Docker images
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: vadv/pg_gatherer_test
        dockerfile: ./docker/test.Dockerfile
        username: vadv
        password: ${{ secrets.DOCKER_TOKEN }}
        cache: ${{ github.event_name != 'schedule' }}
        tags: latest

    - name: Test in docker image
      run: docker run --rm vadv/pg_gatherer:test bash -ec "make test_in_docker"

    - name: Build and push Docker images
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: vadv/pg_gatherer
        dockerfile: ./docker/release.Dockerfile
        username: vadv
        password: ${{ secrets.DOCKER_TOKEN }}
        cache: ${{ github.event_name != 'schedule' }}
        tags: "latest"
