name: test-and-release
on: [push]
jobs:

  test:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repo
      uses: actions/checkout@v1

    - name: Build test docker image
      run: docker build -t test . -f ./docker/test.Dockerfile

    - name: Test in docker image
      run: docker run --rm test bash -ec "make test_in_docker"

  release:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Build and push Docker images
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: vadv/pg_gatherer
        dockerfile: ./docker/release.Dockerfile
        username: vadv
        password: ${{ secrets.DOCKER_TOKEN }}
        tag_names: true
