name: test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v1
    - name: Build test docker image
      run: docker build -t pg_gatherer_test . -f ./docker/test.Dockerfile
    - name: Test in docker image
      run: docker build -t pg_gatherer_test . -f ./docker/test.Dockerfile