name: test
on: [push]
jobs:
  build-image-and-test:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repo
      uses: actions/checkout@v1

    - name: Build pre-test docker image
      run: docker build -t test . -f ./docker/pre-test.Dockerfile

    - name: Test in docker image
      run: docker run --rm test bash -ec "make test_in_docker"
